[build]
  # 빌드 명령어
  command = "npm run build"
  
  # 배포할 디렉토리
  publish = "dist"
  
  # 환경 변수 설정
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# 리다이렉트 규칙
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 보안 헤더
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' https://generativelanguage.googleapis.com https://raw.githack.com https://threejs.org https://cdn.jsdelivr.net; media-src 'self' blob:;"

# 환경 변수 (Netlify 대시보드에서 설정)
# GEMINI_API_KEY = "your-api-key-here"

# 빌드 최적화
[build.processing]
  skip_processing = false

# 함수 설정 (필요시)
[functions]
  directory = "netlify/functions" 